### ISSUE TITLE
Exiting of the satalite tool mode

### ISSUE THREAD

**Issue by ByPS128** [LuminaSapphira/orbital-scanner#1]
Hi,
after I use CTRL+U to enter the satelite chunk selector, I am unable to leave it, exit the mode.
When I grab whatever from hotbar, it will terminate the selection mode.
Is there any other way to exit the mode?
Repeated pressing of the hotkey does not have this effect.

**Comment by LuminaSapphira** [comment]
The satellite chunk selector is a 'selector' type item. Similar to blueprint or copy/paste or the deconstruction planner. There isn't a 'mode' you go into, simply holding the item (given to you by either the shortcut or the hotkey) is all that is necessary. By default, you can use "Q" to clear your hand from a selected item (general factorio tip). 

As an aside - though the shortcut gives you the item, when it is no longer in your hand it is automatically and immediately removed from your inventory.

**Comment by ByPS128** [comment]
You're right, the Q key works great as it does on other tools. Thanks for the detailed explanation and also for the mod. it's really straight ;)
